apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
spec:
  selector:
    matchLabels:
      app: nexus
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: my-nexus-image:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-volume
              mountPath: /nexus-data
      volumes:
        - name: nexus-volume
          persistentVolumeClaim:
            claimName: nexus-pvc
  strategy:
    type: Recreate